# Setup
title:               Hype 2022
tagline:             'Gauging Levels of Misreprentation and Misinformation in Privacy Policies'
description:         'A <a href="https://diri.isb.edu/en.html" target="_blank">DIRI</a> initiative to further the clarification of collected data'
url:                 https://festusdrakon.github.io
baseurl:             /Hype2022
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              DJ
  url:               https://twitter.com/dhananjayjindal
  email:             djindal211@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.0.0
google_analytics_id: #UA-XXXX-Y
